# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('nodename', models.CharField(max_length=15, null=True)),
                ('sshport', models.IntegerField()),
                ('rootpwd', models.CharField(max_length=20)),
                ('status', models.IntegerField(null=True)),
                ('asset_num', models.CharField(blank=True, max_length=50)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('up_time', models.CharField(blank=True, max_length=50)),
                ('cpu_model', models.CharField(blank=True, max_length=100)),
                ('cpu_num', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=30)),
                ('disk', models.CharField(blank=True, max_length=255)),
                ('disk_vender', models.CharField(blank=True, max_length=255)),
                ('aladin', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True, max_length=200)),
                ('graphics', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nodes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Projects'),
        ),
    ]
