# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
