# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_assetinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Projects'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='sshport',
            field=models.IntegerField(),
        ),
    ]
