# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180513_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assetinfo',
            new_name='nodes',
        ),
        migrations.AlterField(
            model_name='nodes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Projects'),
        ),
    ]
