# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180513_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Projects'),
        ),
    ]
