# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20180513_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='aladin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nodes',
            name='asset_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nodes',
            name='asset_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nodes',
            name='cpu_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nodes',
            name='disk',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nodes',
            name='disk_vender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nodes',
            name='memory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='nodes',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nodes',
            name='remark',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nodes',
            name='up_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nodes',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Projects'),
        ),
    ]
